server:
  port: 9201
spring:
  application:
    name: cassandra-demo-restful
  data:
    cassandra:
      contact-points: 34.221.173.135 #[localhoast]
      port: 9042
      keyspace-name: demo_key_space
      schema-action: create_if_not_exists
